global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'promndnode'
    scrape_interval: 5s
    static_configs:
      - targets: 
          - 'localhost:9090'
          - 'target_host:9100'

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: target_host:9115

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'target_host:8080'
