---
blackbox_exporter_version: 0.18.0
blackbox_exporter_binary_url: "https://github.com/{{ _blackbox_exporter_repo }}/releases/download/v{{ blackbox_exporter_version }}/\
                               blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] |
                               default(ansible_architecture) }}.tar.gz"
blackbox_exporter_skip_install: false

blackbox_exporter_web_listen_address: "0.0.0.0:9115"

blackbox_exporter_cli_flags: {}
# blackbox_exporter_cli_flags:
#   log.level: "warn"

blackbox_exporter_configuration_modules:
http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [] 
      method: GET
