---
- name: Install Prometheus using Docker
  hosts: local
  become: true
  vars:
    prometheus_version: "2.22.0"
    

  tasks:
  - name: Create Prometheus directory
    file:
      path: /etc/prometheus
      state: directory
  
  tasks:
  - name: Create Grafana directory
    file:
      path: /var/lib/grafana 
      state: directory

  tasks:
  - name: Create BlackBox-Exporter directory 
    file:
      path: /etc/blackbox_exporter
      state: directory

  - name: Start Prometheus container
    docker_container:
      name: prometheus
      image: prom/prometheus
      ports:
        - "9090:9090"
      volumes:
        - /home/ubuntu/prometheus.yml:/etc/prometheus
      restart_policy: always

  - name: Start Grafana container
    docker_container:
      name: grafana
      image: grafana/grafana
      ports:
        - "3000:3000"
      volumes:
        - /home/ubuntu/grafana-data:/var/lib/grafana
      restart_policy: always

  - name: Start BlackBox-Exporter container
    docker_container:
      name: blackbox
      image: prom/blackbox-exporter
      ports: 
        - "9115:9115"
        volumes:
          - /home/ubuntu/blackbox.yml:/etc/blackbox_exporter
        restart_policy: always


