---
- hosts: local
  become: true

  vars:
    prometheus_version: 2.30.0
    prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    prometheus_install_dir: /opt/prometheus

  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
        state: present

    - name: Download Prometheus
      get_url:
        url: "{{ prometheus_download_url }}"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: "{{ prometheus_install_dir }}"
        remote_src: true
        extra_opts: "--strip-components=1"
        creates: "{{ prometheus_install_dir }}/prometheus"

    - name: Create Prometheus user
      user:
        name: prometheus
        system: true
        shell: /usr/sbin/nologin

    - name: Create Prometheus data directory
      file:
        path: /var/lib/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Create Prometheus configuration directory
      file:
        path: /etc/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Copy Prometheus configuration file
      copy:
        src: /home/ubuntu/prometheus/prometheus.yml
        dest: /etc/prometheus/
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Create Prometheus service file
      copy:
        src: prometheus.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes
