---
- name: Install Prometheus using Docker
  hosts: local
  become: true
  vars:
    prometheus_version: "2.22.0"
    prometheus_data_directory: "/var/lib/prometheus"

  tasks:
  - name: Create Prometheus data directory
    file:
      path: /home/ubuntu/prometheus
      state: directory
  
  tasks:
  - name: Create Grafana data directory
    file:
      path: /home/ubuntu/grafana
      state: directory

  tasks:
  - name: Create BlackBox-Exporter data directory 
    file:
      path: /home/ubuntu/BlackBox
      state: directory

  - name: Start Prometheus container
    docker_container:
      name: prometheus
      image: prom/prometheus
      ports:
        - "9090:9090"
      volumes:
        - /home/ubuntu/prometheus.yml
      restart_policy: always

  - name: Start Grafana container
    docker_container:
      name: garfana
      image: grafana/grafana
      ports:
        - "3000:3000"
      restart_policy: always

  - name: Start BlackBox-Exporter container
    docker_container:
      name: blackbox
      image: prom/blackbox-exporter
      ports: 
        - "9115:9115"
        volumes:
          - /home/ubuntu/blackbox.yml
        restart_policy: always

